// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Less.Sup.WebApi.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506301048582_Update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
